### ISSUE TITLE
Obsługa post/get w formularzu do logowania

### ISSUE THREAD

**Issue by marcioq00** [marcioq00/Mantis#5]
Musisz obsłużyć metody post i get z formularza do logowania.
Od czego zacząć:
1. Dodanie w folderze public/login.html atrybutów do formularza (atrybut name) oraz określić metodę i akcję
2. W folderze routes/login.js dodać router dla post oraz przekierować do kontrolera
3. Stworzenie kontrolera do obsługi loginu

Całe te zadanie już zrobiłem dla register, możesz sobie zobaczyć jak tam jest, tutaj będzie praktycznie to samo

**Comment by P-Maniac** [comment]
Zrobilem igt push, ale sam nie wiem czy taki kod, nie czaje tego do konca.

**Comment by marcioq00** [comment]
Nie pushuje się na maina, tylko na osobne branche jak coś
